services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dq_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      PYDEVD_DISABLE_FILE_VALIDATION: "1" 
      PYTHONUNBUFFERED: "1"
    depends_on:
      postgres:
        condition: service_healthy

  great_expectations:
    image: nginx:alpine
    container_name: great_expectations
    ports:
      - "8080:80"
    volumes:
      - ./gx/uncommitted/data_docs/local_site:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    user: "root"
    env_file:
      - .env
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  superset_home: